### ISSUE TITLE
Script execution policies interfere...

### ISSUE THREAD

**Issue by iarna** [felixrieseberg/npm-windows-upgrade#1]
So when I first tried this (on win 7) I got:

> Error:  (x86)\nodejs\node_modules\npm-windows-upgrade\powershell\upgrade-npm.ps1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at http://go.microsoft.com/fwlink/?LinkID=135170.

Now, it was easy enough to work around this with:

    Set-ExecutionPolicy Unrestricted -Scope CurrentUser

But it seems like this should be documented or tested for or something?

**Comment by felixrieseberg** [comment]
Agreed!

**Comment by felixrieseberg** [comment]
Just to add to this: We're now also warning if the SecPolicy isn't straight up unrestricted.
