### ISSUE TITLE
Node v7.1.0 Compatibility Issue?

### ISSUE THREAD

**Issue by jwuliger** [felixrieseberg/npm-windows-upgrade#101]
Hello,

I just upgraded to Node v7.1.0 on a Windows 10 Machine. I have been using npm-windows-upgrade for a long time now. Love the tool. I am not sure if there is an issue with this tool or with the Node Version. I am able to install npm-windows-upgrade without a problem. When I try to run npm-windows-upgrade I get this message in Powershell:

```
(node:13328) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: write EINVAL
(node:13328) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Thanks for any help!

**Comment by felixrieseberg** [comment]
Thanks for the report! To be clear, did things work for you with Node 7.0?

**Comment by jwuliger** [comment]
Hello. Yes It works fine on 7.0, It looks like other packages are having trouble as well though. I am just reverting back to 7.0

**Comment by g0ld3lux** [comment]
im facing same issue here , is this resolve? any hint to fix this

**Comment by redstrike** [comment]
I want to report the same issue.
**npm-windows-upgrade** run fine on node 7.0, but cannot on node 7.1

**Comment by amurad** [comment]
Same issue, worked on 7.0, but not working on 7.1

**Comment by almothafar** [comment]
Same issue : 

```
npm-windows-upgrade v3.1.0
(node:12280) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: write EINVAL
(node:12280) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are
 not handled will terminate the Node.js process with a non-zero exit code.
tty.js:76
  var err = this._handle.getWindowSize(winSize);
                        ^

TypeError: Cannot read property 'getWindowSize' of null
    at WriteStream._refreshSize (tty.js:76:25)
    at process.on (internal/process/stdio.js:16:43)
    at emitNone (events.js:91:20)
    at process.emit (events.js:185:7)
    at Signal.wrap.onsignal (internal/process.js:200:44)
```

**Comment by felixrieseberg** [comment]
The bug is known upstream and is with Node, but I'll see if there's a way for us to get around it.

Reference: https://github.com/nodejs/node/issues/9542

**Comment by felixrieseberg** [comment]
Alright, seems like there's nothing we can do. Given that this breaks a whole range of important modules (react, mocha, electron, etc) I'd recommend that everyone downgrades to 7.0 until this bug is fixed.

In the meantime, I published a new version of `npm-windows-upgrade` that will warn users if they are running on Node v7.1.
