### ISSUE TITLE
It's not working with Windows 7

### ISSUE THREAD

**Issue by RHMason** [felixrieseberg/npm-windows-upgrade#104]
I got a successful install but when trying to execute I just get the message:

'npm-windows-upgrade' is not recognized as an internal or external command,
operable program or batch file.

**Comment by felixrieseberg** [comment]
Hi! Which command did you run to install it? It's important that you install it with the `--global` flag - and that your initial npm was installed correctly.

**Comment by tonymiao2012** [comment]
I have a similar issue. I tried command line: npm-windows-upgrade --npm-version latest in CMD. But got an error "Scripts cannot be executed on this system". My platform is Windows 7 64bit. Didn't know what's going on.

**Comment by tonydearaujo** [comment]
Windows users, if **-g** is not being recognized by the system, place it at the very end of the instruction (rightmost side) to see if it solves your problem.

**Comment by ethankale** [comment]
I have the same issue.  Moving -g or --global to the end of the instruction makes no difference.  I don't think this is resolved yet.

Initial command: `npm install --global --production npm-windows-upgrade`
Also tried: `npm install --production npm-windows-upgrade -g`
Also tried: `npm install --production npm-windows-upgrade --global`

**Comment by bbottema** [comment]
Indeed, this issue persists for me as well. Tried above suggestions.
