### ISSUE TITLE
Unhandled 'error' when trying to upgrade

### ISSUE THREAD

**Issue by Kachilero** [felixrieseberg/npm-windows-upgrade#12]
Tried to upgrade and immediately got error:

![npm_upgrade_error](https://cloud.githubusercontent.com/assets/5316481/8697774/671e11b8-2abd-11e5-98a6-572cfb8130fb.png)

Ran the package in the GitHub shell, with and without the suggested `SetExecutionPolicy` (as per the readme.) Also tried to run in the command prompt as administrator and got an error when attempting to use `SetExecutionPolicy`.

**Comment by felixrieseberg** [comment]
Hey! I'm afraid that your version of Windows *might* be too old - which one are you running?

**Comment by Kachilero** [comment]
@felixrieseberg I'm running Windows 7 Home Premium (2009) Service Pack 1.

**Comment by felixrieseberg** [comment]
So your version of Windows is okay (even if not great), but the PowerShell you're using is a little bit outdated and no longer supported. Make sure you have all the latest updates for Windows 7 installed and download this upgrade: http://www.microsoft.com/en-us/download/details.aspx?id=40855.

That should fix your issue.
