### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by MMSharif** [felixrieseberg/npm-windows-upgrade#120]
C:\Program Files>npm install
npm WARN saveError ENOENT: no such file or directory, open 'C:\Program Files\package.json'
npm WARN saveError EPERM: operation not permitted, open 'C:\Program Files\package-lock.json.1018476909'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Program Files\package.json'
npm WARN Program Files No description
npm WARN Program Files No repository field.
npm WARN Program Files No README data
npm WARN Program Files No license field.

**Comment by felixrieseberg** [comment]
I'm not sure what the error report here is. You ran `npm install` in Program Files.
