### ISSUE TITLE
Some Host Script Error 800A03F6

### ISSUE THREAD

**Issue by mdsManu** [felixrieseberg/npm-windows-upgrade#122]
Hey I've got some Error during the installation :c

![2018-02-11 12_21_22-npm](https://user-images.githubusercontent.com/32361781/36073303-acd89efa-0f2e-11e8-83fa-1e3194bc905e.png)

![2018-02-11 12_24_49-administrator_ windows powershell](https://user-images.githubusercontent.com/32361781/36073330-0afc9ac2-0f2f-11e8-8a2b-32d2ae164bd0.png)

This is the Error Message hope u guys can help me :D

**Comment by felixrieseberg** [comment]
I believe that this was caused by Windows trying to open the JavaScript file itself 🙈
