### ISSUE TITLE
SyntaxError: Unexpected token ♀

### ISSUE THREAD

**Issue by laggingreflex** [felixrieseberg/npm-windows-upgrade#13]
Getting this error when trying to run 

    npm-windows-upgrade 0.2.6
    ? This tool will upgrade npm. Do you want to continue? Yes
    undefined:1
    ♀
    ^
    SyntaxError: Unexpected token ♀
        at Object.parse (native)
        at C:\...\AppData\Roaming\npm\node_modules\npm-windows-upgrade\bin\npm-windows-upgrade:72:17
        at ChildProcess.exithandler (child_process.js:187:7)
        at emitTwo (events.js:87:13)
        at ChildProcess.emit (events.js:172:7)
        at maybeClose (internal/child_process.js:764:16)
        at Socket.<anonymous> (internal/child_process.js:319:11)
        at emitOne (events.js:77:13)
        at Socket.emit (events.js:169:7)
        at Pipe._onclose (net.js:467:12)

Windows 8.1  PowerShell version 4

**Comment by felixrieseberg** [comment]
Het, thanks for reporting! I'm a little bit baffled - I'm not entirely sure what is going on. To help you to upgrade (and me to understand what happened here), can you try the following two things:

1) Run `npm view npm versions --json`. That's what's failing here, and I'd love to know why - that being said, we don't really need it.
2) So if nothing else fails miserably, this should work `npm-windows-upgrade --version:3.1.0`

**Comment by laggingreflex** [comment]
Thanks for the response. 

1) It gives a long array of versions going from "1.1.25" to "3.1.2" (including "3.1.0")
2) That command gives the same error as well.

**Comment by laggingreflex** [comment]
I put a `console.log(stdout)` [at line 71][L71] and its output has that character `♀` at the beginning for some reason (the rest of the output the fine, i.e. the array of versions). That's I think where the error is coming from. I have no idea why though...

[L71]: https://github.com/felixrieseberg/npm-windows-upgrade/blob/master/bin/npm-windows-upgrade#L71

**Comment by felixrieseberg** [comment]
...I'm so confused. I really wish I could help you, but I have no idea why that's happening. 

To help you: The upgrader is essentially just a small ps1 script that you can also run manually. If you open `C:\...\AppData\Roaming\npm\node_modules\npm-windows-upgrade\powershell`, you can run the `upgrade-npm.ps1` script directly, bypassing Node. Be warned though, that ♀ character isn't giving me great confidence ;)
