### ISSUE TITLE
npm 3.1.2 and global packages?

### ISSUE THREAD

**Issue by robertbaker** [felixrieseberg/npm-windows-upgrade#14]
I did a clean install of Node 12.7. I installed this and updated to npm 3.1.2. I installed some global packages, which installed in Program Files\NPM.

The global packages used to be installed in %appdata%.

%localappadata% is a better alternative.

Is this an issue with this script or just NPM  3.1.2. I'm asking here because I didn't see anything in the changelog about it for npm.

**Comment by felixrieseberg** [comment]
Hey! Thanks for reporting, but this issue would be better in the npm repo - the upgrader doesn't change anything about npm, it just updates it :smile:. I'll close this issue, but feel free to ask more questions!
