### ISSUE TITLE
Unpexpected token [ 

### ISSUE THREAD

**Issue by kand617** [felixrieseberg/npm-windows-upgrade#15]
Getting the following error when running the upgrade command

![image](https://cloud.githubusercontent.com/assets/5092518/8764057/147c5350-2e11-11e5-9211-164bbceaec1a.png)

**Comment by felixrieseberg** [comment]
Hey @kand617, thanks for reporting! Can you tell me which version of Node, npm, and Windows you're running? Are you running the script as Administrator?
