### ISSUE TITLE
Error: spawn powershell.exe ENOENT

### ISSUE THREAD

**Issue by MahmoudMabrok** [felixrieseberg/npm-windows-upgrade#150]
while executing `npm-windows-upgrade` i got 
```
npm-windows-upgrade v6.0.1
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn powershell.exe ENOENT
←[90m    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)←[39m
←[90m    at onErrorNT (internal/child_process.js:456:16)←[39m
←[90m    at processTicksAndRejections (internal/process/task_queues.js:80:21)←[39m
Emitted 'error' event on ChildProcess instance at:
←[90m    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)←[39m
←[90m    at onErrorNT (internal/child_process.js:456:16)←[39m
←[90m    at processTicksAndRejections (internal/process/task_queues.js:80:21)←[39m {
  errno: ←[32m'ENOENT'←[39m,
  code: ←[32m'ENOENT'←[39m,
  syscall: ←[32m'spawn powershell.exe'←[39m,
  path: ←[32m'powershell.exe'←[39m,
  spawnargs: [ ←[32m'-NoProfile'←[39m, ←[32m'-NoLogo'←[39m, ←[32m'Get-ExecutionPolicy'←[39m
 ]
}

```

**Comment by MahmoudMabrok** [comment]
Complete solution is 
- First add **Poweshell** to **PATH** as  `%SystemRoot%/system32/WindowsPowerShell/v1.0`.
- open **powershell** as **admin** and write this command `Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force`.
- last thing fire `npm-windows-upgrade`.

**Comment by kmaniruddin28** [comment]
> Complete solution is
> 
> * First add **Poweshell** to **PATH** as  `%SystemRoot%/system32/WindowsPowerShell/v1.0`.
> * open **powershell** as **admin** and write this command `Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force`.

**Comment by thriftykapila** [comment]
> Complete solution is
> 
> * First add **Poweshell** to **PATH** as  `%SystemRoot%/system32/WindowsPowerShell/v1.0`.
> * open **powershell** as **admin** and write this command `Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force`.
> * last thing fire `npm-windows-upgrade`.

this doesn't solves the issue

**Comment by Sourabh42** [comment]
> > Complete solution is
> > 
> > * First add **Poweshell** to **PATH** as  `%SystemRoot%/system32/WindowsPowerShell/v1.0`.
> > * open **powershell** as **admin** and write this command `Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force`.

Thanks For Solution

**Comment by pratama1224** [comment]
Which path to installing  **user variable** or **system variable** ?
