### ISSUE TITLE
You wanted to install npm 7.6.1, but the installed version is 6.14.11.

### ISSUE THREAD

**Issue by era5mx** [felixrieseberg/npm-windows-upgrade#168]
You wanted to install npm 7.6.1, but the installed version is 6.14.11.

A common reason is an attempted "npm install npm" or "npm upgrade npm". As of today, the only solution is to completely uninstall and then reinstall Node.js. For a small tutorial, please see https://github.com/felixrieseberg/npm-windows-upgrade#usage.

Please consider reporting your trouble to https://aka.ms/npm-issues.

Debug Information:

node: 14.16.0 | v8: 8.4.371.19-node.18 | uv: 1.40.0 | zlib: 1.2.11 | brotli: 1.0.9 | ares: 1.16.1 | modules: 83 | nghttp2: 1.41.0 | napi: 7 | llhttp: 2.1.3 | openssl: 1.1.1j | cldr: 37.0 | icu: 67.1 | tz: 2020a | unicode: 13.0 | os: win32 x64

**Comment by ghost** [comment]
I'm also seeing this...did you by chance load nodejs and npm via the Windows nvm as directed here?
https://docs.microsoft.com/en-us/windows/nodejs/setup-on-windows

npm-windows-upgrade v6.0.1
? Which version do you want to install? 7.6.3
Checked system for npm installation:
According to PowerShell: C:\Program Files\nodejs
According to npm:        C:\Program Files\nodejs
Decided that npm is installed in C:\Program Files\nodejs
Upgrading npm... -

Upgrading npm (fallback method)... \

You wanted to install npm 7.6.3, but the installed version is 6.14.11.

A common reason is an attempted "npm install npm" or "npm upgrade npm". As of today, the only solution is to completely uninstall and then reinstall Node.js. For a small tutorial, please see https://github.com/felixrieseberg/npm-windows-upgrade#usage.

Please consider reporting your trouble to https://aka.ms/npm-issues.

Debug Information:

node: 14.16.0 | v8: 8.4.371.19-node.18 | uv: 1.40.0 | zlib: 1.2.11 | brotli: 1.0.9 | ares: 1.16.1 | modules: 83 | nghttp2: 1.41.0 | napi: 7 | llhttp: 2.1.3 | openssl: 1.1.1j | cldr: 37.0 | icu: 67.1 | tz: 2020a | unicode: 13.0 | os: win32 x64 | OS Name: Microsoft Windows 10 Enterprise
OS Version: 10.0.19042 N/A Build 19042

**Comment by era5mx** [comment]
npm-windows-upgrade it worked for me, thank you very much
