### ISSUE TITLE
npm path problem?

### ISSUE THREAD

**Issue by lovesmilesha** [felixrieseberg/npm-windows-upgrade#17]
I install npm-windows-upgrade,but when i use it to update my npm,have the problems:
npm-windows-upgrade 0.2.6
? This tool will upgrade npm. Do you want to continu
Scripts cannot be executed on this system.
To fix this issue, please run the command below as A
Set-ExecutionPolicy Unrestricted -Scope CurrentUser

**Comment by lovesmilesha** [comment]
sorry,i don't see the way in your notice.

**Comment by NNM11** [comment]
Add the "-Force" parameter to the Set-ExecutionPolicy command.  This works for me in Windows 10 CTP.

**Comment by felixrieseberg** [comment]
Thanks @NNM11 for the hint - @lovesmilesha let me know if that works for you. To make it clear, open up PowerShell (right click, select "Run as Administrator") and enter this before running npm-windows-upgrade:

`Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force`

I'll close this in the meantime, but feel free to let me know if you have any issues!

**Comment by lovesmilesha** [comment]
yes
@felixrieseberg 
follow your way.To make it clear, open up PowerShell (right click, select "Run as Administrator") and enter this before running npm-windows-upgrade:

Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force
-----------------------------------------------------------------------------------------
runs well.think you!
