### ISSUE TITLE
npm WARN EPACKAGEJSON

### ISSUE THREAD

**Issue by dvlsg** [felixrieseberg/npm-windows-upgrade#19]
I am receiving the following error when executing `npm-windows-upgrade` (sorry for the horrible formatting, just dumping a copy/paste from my cmd window):

    You wanted to install npm 3.1.3, but the installed version is2.11.3.
    Please consider reporting your trouble to http://aka.ms/npm-issues.
    Here is the output from the upgrader script:
    [ 'C:\\Users\\Dave\\AppData\\Roaming\\npm\\npm -> C:\\Users\\Dave\\AppData\\Roam
    ing\\npm\\node_modules\\npm\\bin\\npm-cli.js\n',
      'C:\\Users\\Dave\\AppData\\Roaming\\npm\n└── npm@3.1.3 \n\n',
      'All done!\r\n' ] [ 'npm',
      ' WARN EPACKAGEJSON C:\\Users\\Dave\\AppData\\Roaming\\npm No description\n',
      'npm ',
      'WARN EPACKAGEJSON C:\\Users\\Dave\\AppData\\Roaming\\npm No repository field.
    \n',
      'npm WARN EPACKAGEJSON C:\\Users\\Dave\\AppData\\Roaming\\npm No README data\n
    ',
      'npm WARN EPACKAGEJSON C:\\Users\\Dave\\AppData\\Roaming\\npm No license field
    .\n' ]

Executing `npm -v` returns `2.11.3` at this point.

I ended up executing `npm install -g npm@3.1.3` and copying the contents of the roaming npm folder to %programfiles%\nodejs\node_modules\npm and ran `npm-windows-upgrade` again for kicks and giggles, and it reported the same warnings, but then counted the upgrade as a success.

Here's my specs:
Node: v0.12.7
Npm: v2.11.3
Windows: 8 x64 Professional
(no IO.js is currently installed, but it was at one point)

**Comment by felixrieseberg** [comment]
Hm, that's too bad - the script managed to install npm, but it was overruled by npm installed in the Node folder. I'll think about a way to force the upgrader to upgrade npm in more than one location.

**Comment by felixrieseberg** [comment]
Actually, I have hopes that the just released version 0.3.2 will fix your issue. Do me a favour and run `npm install -g npm-windows-upgrade` and `npm-windows-upgrade` again.

**Comment by dvlsg** [comment]
Worked great! Or mostly, anyways. I had to `npm uninstall -g npm-windows-upgrade` first, but after that it went smoothly.

I suppose I was upgrading from my manually copied npm 3.1.3 to npm 3.2.0, though. If you would like the additional test, I can wipe out all of my nodejs/npm files and then attempt an upgrade from npm 2 to npm 3.2.0 again.

**Comment by felixrieseberg** [comment]
That's very kind, but I'm happy with the results so far. Thank you very much!
