### ISSUE TITLE
'Could not find installation location'

### ISSUE THREAD

**Issue by dlandis** [felixrieseberg/npm-windows-upgrade#21]
Here is the error:

    [ 'Could not find installation location (assumed in C:\\Program Files (x86)\\nodejs) - aborting upgrade\r\n' ] []

By default nodejs installed at `C:\\nodejs` for me so I would assume there is some way to configure npm-windows-upgrade to look in another location? Is there, maybe, a script parameter to pass in representing the installed location of nodejs?

Thanks

**Comment by felixrieseberg** [comment]
Hey @dlandis, thank you very much for reporting - and the good suggestion! I just build and released 0.2.10, which has a `--npmPath` parameter. Let me know how that works for you. Again, thanks :clap:!

**Comment by dlandis** [comment]
Thanks for responding so quickly. After I got the error I switched my node.js to the other location (Program Files (x86)), so I didn't get a chance to test your change yet.
