### ISSUE TITLE
Override "Confirm to update" prompt

### ISSUE THREAD

**Issue by BergWerkGIS** [felixrieseberg/npm-windows-upgrade#25]
First things first: Great tool, thanks a lot!

**Feature Proposal:**

It would be nice to be able to override the update confirmation prompt with a parameter, e.g. `--no-prompt` or `--no-confirmation`, just like `--version`.

**Background:**

I'm working on several native node modules on an automated build system (AppVeyor).
The modules are compiled with different node versions.
To get consistent `npm` behaviour I would like to use the same npm version with all node versions I'm targeting.

As quick fix, I completely removed the prompt for my automated builds:
https://github.com/felixrieseberg/npm-windows-upgrade/blob/c26626413c09197940364c86b3b3c286cace144a/bin/npm-windows-upgrade#L268-L272

**Comment by felixrieseberg** [comment]
Hey, thanks for suggesting! Will be implemented :)

**Comment by felixrieseberg** [comment]
Thanks again! This feature is now in 0.4.0, which was just published :+1:

**Comment by BergWerkGIS** [comment]
:+1: Thanks for the fast fix!
