### ISSUE TITLE
Override version selection

### ISSUE THREAD

**Issue by thany** [felixrieseberg/npm-windows-upgrade#26]
Would be nice to automatically select the latest version, so (together with #25) we can do a fully unattended upgrade. Something like
```
npm-windows-upgrade --quiet --version:latest
```
Or something. Currently doesn't work, as there's no version, or an alias for a version, called "latest".

**Comment by felixrieseberg** [comment]
Hey @thany, thanks for the suggestion! That being said, this already works :santa:. The only trouble is that npm's `latest` still points to the latest npm@2, whereas I keep recommending to people that npm@3 is amazing for anyone using Windows.

I'll close this in the meantime, but feel free to reopen if I misunderstood you!
