### ISSUE TITLE
Scripts cannot be executed on this system

### ISSUE THREAD

**Issue by anlex2013** [felixrieseberg/npm-windows-upgrade#27]
![default](https://cloud.githubusercontent.com/assets/8686739/9150612/24214cde-3e15-11e5-9392-c6293fa867e2.PNG)
![default](https://cloud.githubusercontent.com/assets/8686739/9150614/4bcef5d8-3e15-11e5-9421-4491cfda3cbf.PNG)
who can help me ?

**Comment by felixrieseberg** [comment]
Can you tell me what the output is in the second screenshot? My Chinese is horrible ;-)

**Comment by anlex2013** [comment]
It was already fine when using powershell as administrator. but thank you at the same time! The other hand, i want to ask you, can you develop cordova using visual studio 2015? do you have some wonderful tutorials about it to give me?

**Comment by felixrieseberg** [comment]
Cool, closing this then. To find out more about Cordova apps and VS, check this out: https://www.visualstudio.com/en-us/features/cordova-vs.aspx
