### ISSUE TITLE
npm-windows-upgrade command not found

### ISSUE THREAD

**Issue by thdoan** [felixrieseberg/npm-windows-upgrade#28]
I have the default installation of Node.js for Windows (node-v0.12.7-x86.msi). After following the instructions on https://www.npmjs.com/package/npm-windows-upgrade and executing `npm-windows-upgrade` in the PowerShell console I got the following error:

```
npm-windows-upgrade : The term 'npm-windows-upgrade' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or   
if a path was included, verify that the path is correct and try again.                                                                                                           
At line:1 char:1                                                                                                                                                                 
+ npm-windows-upgrade                                                                                                                                                            
+ ~~~~~~~~~~~~~~~~~~~                                                                                                                                                            
    + CategoryInfo          : ObjectNotFound: (npm-windows-upgrade:String) [], CommandNotFoundException                                                                          
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by felixrieseberg** [comment]
Hey @thdoan, this should be easy to fix! Did you install it globally, using the `npm install -g npm-windows-upgrade`?

**Comment by thdoan** [comment]
@felixrieseberg Yes, I did. However, I managed to fix it using the manual solution given on the npm-windows-upgrade website, so I'm going to close this.

**Comment by wesleymusgrove** [comment]
Hi @thdoan, I'm also getting this error after running `npm install -g npm-windows-upgrade` in Powershell as Administrator.  Can you point to which set of "manual solution" instructions helped you solve this?

**Comment by thdoan** [comment]
@wesleymusgrove https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows

**Comment by kokarn** [comment]
I'm also seeing this. Exactly the same error as well.
Doing it the manual way kinda defeats the purpose tho :(
