### ISSUE TITLE
npm install require admin.

### ISSUE THREAD

**Issue by centure** [felixrieseberg/npm-windows-upgrade#31]
node js installed on program files. and therefore npm is. older node did roaming. but after using this module it turned out the the roaming does not exist. and npm is tring to write to program files. which fails. any idea how to over come this issue? thanks!!

**Comment by felixrieseberg** [comment]
Hey @centure,

`npm-windows-upgrade` tries to find your npm location and installs it where it was found before - with a few fallbacks, in case things go wrong. It does not delete anything, so roaming should still be around.

There's a simple command to define the global installation location for your node modules:
```
npm config --global set prefix "%appdata%\npm"
npm config --global set cache "%appdata%\npm-cache"
```

Also, open up an Explorer window and enter `%appdata%` into the address field. Ensure that both `npm` and `npm-cache` exist.

That should fix your issue, so I'm closing this - but do let me know if you run into any more trouble!

**Comment by centure** [comment]
Thanks. Seems to work good :)
