### ISSUE TITLE
Error when I launch the commande

### ISSUE THREAD

**Issue by arnaudhuc** [felixrieseberg/npm-windows-upgrade#32]
Hi,

When I launch the basic commande : npm-windows-updrade and say Yes I have this error : 

undefined:1
♀
^
SyntaxError: Unexpected token ♀
    at Object.parse (native)
    at C:\Users\a.huc\AppData\Roaming\npm\node_modules\npm-windows-upgrade\bin\npm-windows-upgrade:79:17
    at ChildProcess.exithandler (child_process.js:742:7)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

How can I correct it ?

**Comment by felixrieseberg** [comment]
Thanks for reporting! I have *no idea* what's going on here, but we're talking to the PowerShell Team and hoping that we'll figure it out :+1:

**Comment by felixrieseberg** [comment]
Well, we have no clue what's going on. If anyone has any idea what I should even look for, I'd appreciate the help.

**Comment by felixrieseberg** [comment]
Closing this for now, as nobody else reported it - and I have no idea what it could possible be.
