### ISSUE TITLE
EPERM issue after using npm-windows-upgrade

### ISSUE THREAD

**Issue by zoamel** [felixrieseberg/npm-windows-upgrade#33]
Hey,
First of all thanks a lot for this great tool! I've managed to update my npm to newest version without any problem. Although after this process I can't install modules without running console as administrator. Currently I am using ConEmu with GitBash and after running for example `npm install -g ember-cli` I get an error:

```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ember-cli"
npm ERR! node v4.0.0
npm ERR! npm  v3.3.2
npm ERR! path c:\Program Files\nodejs\node_modules\.staging
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall mkdir

npm ERR! Error: EPERM: operation not permitted, mkdir 'c:\Program Files\nodejs\node_modules\.staging'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, mkdir 'c:\Program Files\nodejs\node_modules\.staging']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: 'c:\\Program Files\\nodejs\\node_modules\\.staging' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\marw\Workspace\npm-debug.log
/c/Program Files/nodejs/npm: line 27:  6072 Signal 112              (core dumped) "$NODE_EXE" "$NPM_CLI_JS" "$@"
```

**Comment by felixrieseberg** [comment]
Hey @zoamel, thanks for reporting! Do you always have to install modules as Administrator - or only global modules? For global modules, requiring admin rights makes sense.

**Comment by zoamel** [comment]
@felixrieseberg only global modules. Although earlier I didn't have to do that, and neither on osx/ubuntu. From what I know, having to install global node modules as admin can cause some unexpected troubles at some point (at least on nix systems)

**Comment by felixrieseberg** [comment]
Hey @zoamel, the behavior is fine on Windows - but if you want to change the location of your global modules (and make them less system-wide), you can do that like so: https://stackoverflow.com/questions/7300132/how-to-use-npm-with-node-exe/9366416#9366416
