### ISSUE TITLE
ExecutionPolicy script is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Gordiievskyi** [felixrieseberg/npm-windows-upgrade#35]
Hi guys I execute the script(Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force) from folder where you tool is located(disk D/npm-windows-upgrade-master\) in cmd(that I run as admin) and see next message:
 'Set-ExecutionPolicy' is not recognized as an internal or external command,
operable program or batch file.

Windows 7 64 bit

**Comment by felixrieseberg** [comment]
Simple fix: Run the command from PowerShell!

**Comment by mishelen** [comment]
Dont work for me: and in cmd, and powershell, in all cases script was runned with admin permission, but I get the same error.
I`m also try to run it from npm folder where its located.
```
PS C:\Users\mishelen\AppData\Roaming\npm> npm-windows-upgrade
npm-windows-upgrade 0.5.1
? This tool will upgrade npm. Do you want to continue? Yes
Scripts cannot be executed on this system.
To fix, run the command below as Administrator in PowerShell and try again:
Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force
```


Windows 7 64 bit

**Comment by tejadivi** [comment]
@mishelen run PowerShell as Administrator .... it worked for me.

**Comment by DeepthiVangapandu** [comment]
run PowerShell as Administrator .... it also worked for me.

**Comment by Lokeshthakur1** [comment]
run PowerShell as Administrato not working

**Comment by HellenNamulinda** [comment]
Running cmd as administrator not working for me

**Comment by te-lyhourt** [comment]
dont run cmd , run PowerShell as Administrato
