### ISSUE TITLE
Breaks Tools for Apache Cordova and VS 2015

### ISSUE THREAD

**Issue by MattHoneycutt** [felixrieseberg/npm-windows-upgrade#36]
If you install VS 2015 first, then use this tool, it will break the Tools for Apache Cordova config so that VS can no longer build Apache Cordova packages.  That's because it changes the -g prefix directory, so vs-tac and all the dependencies, which are installed under AppData by default, will appear to be missing.

**Comment by felixrieseberg** [comment]
Yeah, we sadly don't have the best record when it comes to Visual Studio and Node. I should probably document that in spite of whatever default behavior npm expects, one can always use `npm config --global set prefix "C:\MyPath"` to set the location.

Thanks for reporting!

**Comment by MattHoneycutt** [comment]
Would running that to switch the prefix back to the old, VS-preferred path
work correctly?  Would it migrate the upgraded version of NPM to the new
(old) prefix location?

On Tue, Sep 29, 2015 at 11:44 PM Felix Rieseberg <notifications@github.com>
wrote:

> Yeah, we sadly don't have the best record when it comes to Visual Studio
> and Node. I should probably document that in spite of whatever default
> behavior npm expects, one can always use npm config --global set prefix
> "C:\MyPath" to set the location.
>
> Thanks for reporting!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/felixrieseberg/npm-windows-upgrade/issues/36#issuecomment-144280344>
> .
>
-- 
*Matt Honeycutt*
*Pluralsight Author & Senior Web Application Architect*
[image: Heroic Applications] <http://heroicapplications.com/>
pluralsight vids <http://www.pluralsight.com/author/matt-honeycutt> | blog
<http://trycatchfail.com/> | website <http://heroicapplications.com/> |
@matthoneycutt <http://twitter.com/matthoneycutt>

**Comment by felixrieseberg** [comment]
Yep, that's exactly what it should do!

**Comment by felixrieseberg** [comment]
Quick addendum: Global modules will be installed in `node_modules` in whatever folder you set as the global prefix. So, if you want modules to end up in `%APPDATA%\Roaming\npm\node_modules`, set the prefix to `%APPDATA%\Roaming\npm\`.

I'll keep this issue open until I update the script to ensure that we're not changing the prefix.

**Comment by felixrieseberg** [comment]
This should actually be fixed in the latest release.
