### ISSUE TITLE
Cannot bind argument to parameter 'Path' because it is null.

### ISSUE THREAD

**Issue by MhSaadany** [felixrieseberg/npm-windows-upgrade#4]
I'm getting this error in `upgrade-npm.ps1`
```
Cannot bind argument to parameter 'Path' because it is null.
 + CategoryInfo          : InvalidData: (:) [upgrade-npm.ps1], ParameterBindingValidationException
 + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,upgrade-npm.ps1
```

**Comment by felixrieseberg** [comment]
Thanks for reporting! I believe that a your issue should have been fixed in the latest version (v0.1.4). Can you update (`npm install -g npm-windows-upgrade@latest`) and try again?

**Comment by BarryThePenguin** [comment]
I receive the same with 0.1.4, I think it's related to #3

**Comment by BarryThePenguin** [comment]
My User PATH
```
C:\Program Files\nodejs\;C:\Users\jonno\AppData\Roaming\npm
```

My System PATH
```
C:\Users\jonno\AppData\Roaming\npm
```

to that effect anyway

**Comment by felixrieseberg** [comment]
Thanks! I'm certain that it's not your fault, but a System variable pointing to a user directory is exactly the kind of mess that brought us here ;-) I'll make sure that this tools solves your needs. I'll keep both issues until then.

**Comment by BarryThePenguin** [comment]
Yeah, that would be my doing... I'm currently doing a fresh install of Node

**Comment by BarryThePenguin** [comment]
A fresh install of node@0.12.5 with npm@2.11.2 leaves me with no npm reference in my System PATH and a single reference to `C:\Users\btp\AppData\Roaming\npm` in my User PATH

I still receive the following
```
C:\Users\btp\AppData\Roaming\npm\node_modules\npm-windows-upgrade\powershell\upgrade-npm.ps1 : Cannot bind argument to parameter 'Path' because it is null.
    + CategoryInfo          : InvalidData: (:) [upgrade-npm.ps1], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,upgrade-npm.ps1
```

**Comment by jdoose** [comment]
Had the same error. In my case I solved it by following option 2:
~~~
Option 2: remove both of

    %ProgramFiles%\nodejs\npm
    %ProgramFiles%\nodejs\npm.cmd
~~~

**Comment by felixrieseberg** [comment]
Thanks to all of you (@jdoose, @MhSaadany, @BarryThePenguin) - This error should now be fixed. For those curious: I checked the wrong path for existence.

**Comment by BarryThePenguin** [comment]
Woo! Looks good here
