### ISSUE TITLE
error running npm install, 'no such file or dir' for mkdirp\b and rimraf\b

### ISSUE THREAD

**Issue by dcolliervb23** [felixrieseberg/npm-windows-upgrade#45]
I am getting the following error while trying to run this command.  Any help would be greatly appreciated.  Thanks!

C:\Users\dcollier
λ Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force
C:\Users\dcollier
λ npm install -g npm-windows-upgrade npm-windows-upgrade
npm WARN install:mkdirp ENOENT: no such file or directory, chmod 'C:\Users\dcollier\AppData\Roaming\npm\node_modules\npm-windows-upgrade\node_modules\mkdirp\b'
npm WARN install:rimraf ENOENT: no such file or directory, chmod 'C:\Users\dcollier\AppData\Roaming\npm\node_modules\npm-windows-upgrade\node_modules\utile\node_modules\rimraf\b'
C:\Users\dcollier\AppData\Roaming\npm
└── (empty)

npm ERR! code 1
C:\Users\dcollier
λ

**Comment by felixrieseberg** [comment]
Hey, one thing that looks weird:

```
npm install -g npm-windows-upgrade npm-windows-upgrade
```

Is that how you entered it?

**Comment by dcolliervb23** [comment]
Yes, I was trying to follow the instructions explicitly and thought that it might be wrapping that last command.  The extra npm-windows-upgrade doesn't have any effect on the outcome though.

**Comment by felixrieseberg** [comment]
Well, they are two commands to be executed after each other ;-) You seem to have trouble installing this tool altogether, which is something we can't really do much about. I'd recommend the good old reboot (to clear potential directory locks) and running the installation as Administrator.

**Comment by dcolliervb23** [comment]
Fixed!  I manually upgraded to 3.3.10 and pointed my registry back to the public one, ran 
npm i -g npm-windows-upgrade
and it worked.  I'm now on 3.3.11.  I'm still not quite sure what my problem was.  Maybe a combo of the older version and the private registry (with connector to public registry).
