### ISSUE TITLE
npm-windows-upgrade is installing wrong version

### ISSUE THREAD

**Issue by vvundela** [felixrieseberg/npm-windows-upgrade#51]
Hi 
when I ran "npm-windows-upgrade" in powershell and choose 3.3.11 as the version to upgrade,system automatically does install for 3.4.1 which is not supposed to happen.Please check the attached file for more details.
Thanks

![npm windows upgrade error](https://cloud.githubusercontent.com/assets/16341682/11880885/5cb76b00-a4d1-11e5-8b71-60cec6dcd72a.PNG)

**Comment by felixrieseberg** [comment]
Thanks for reporting -  and you're sure that you didn't have 3.4.1 previously installed?

**Comment by vvundela** [comment]
Yes I haven’t installed 3.4.1.

Thanks
