### ISSUE TITLE
Error updating npm 3.5.2 to 3.5.3

### ISSUE THREAD

**Issue by RushabhJoshi** [felixrieseberg/npm-windows-upgrade#52]
I was not able to install any packages with npm(some windows NT error), so I update node and tried to update npm

[https://github.com/felixrieseberg/npm-windows-upgrade](https://github.com/felixrieseberg/npm-windows-upgrade) as this suggested.

I started power shell as administrator
Entered command as suggested
1. Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force
2. npm install -g npm-windows-upgrade

on 
npm install -g npm-windows-upgrade
I selected 3.5.3 
this shows me the error 

```
Upgrading... /Error:  npm
Upgrading... -Error:
Error:  WARN
Error:
Error:  enoent
Error:   ENOENT: no such file or directory, open 'C:\Program Files\nodejs\package.json'

Error:  npm
Error:
Error:  WARN
Error:   nodejs No description

Error:  npm WARN nodejs No repository field.
npm WARN nodejs No README data
npm WARN nodejs No license field.

Upgrading... /

You wanted to install npm 3.5.3, but the installed version is3.5.2.
Please consider reporting your trouble to http://aka.ms/npm-issues.
Here is the error:
```

**Comment by kurtextrem** [comment]
Same for me, but I want to upgrade from 3.3.6.

**Comment by felixrieseberg** [comment]
Hey, thanks for reporting! I just pushed out an update that attempts a fallback installation if the primary method fails - also, I fixed a few small bugs. Would you mind testing that new version?

**Comment by kurtextrem** [comment]
Working great now - merry christmas!

**Comment by RushabhJoshi** [comment]
Done...! :+1: 
and merry Christmas
