### ISSUE TITLE
Upgrade fails with Node.js 5.4.1 and npm 3.5.4

### ISSUE THREAD

**Issue by atom0s** [felixrieseberg/npm-windows-upgrade#54]
Clean install of Node.js 5.4.1, attempting to upgrade npm yields the following:

    C:\Windows\system32> npm-windows-upgrade
    npm-windows-upgrade 1.2.0
    ? This tool will upgrade npm. Do you want to continue? Yes
    ? Which version do you want to install? 3.5.4
    Upgrading... /Error:  npm
    Error:
    Error:  WARN ENOENT ENOENT: no such file or directory, open 'C:\Program Files\nodejs\package.json'

    Error:  npm
    Error:   WARN EPACKAGEJSON nodejs No description

    Error:  npm
    Error:  WARN EPACKAGEJSON nodejs No repository field.

    Error:  npm WARN
    Error:   EPACKAGEJSON nodejs No README data

    Error:  npm WARN
    Error:   EPACKAGEJSON nodejs No license field.

    Error:  npm
    Error:   WARN EBUNDLEOVERRIDE Replacing bundled node_modules\npm\node_modules\init-package-json with new installed versi
    on

    Error:  npm
    Error:  WARN EBUNDLEOVERRIDE Replacing bundled node_modules\npm\node_modules\node-gyp with new installed version

    Error:  npm
    Error:  WARN EBUNDLEOVERRIDE Replacing bundled node_modules\npm\node_modules\npm-install-checks with new installed versi
    on

    Error:  npm
    Error:   WARN EBUNDLEOVERRIDE Replacing bundled node_modules\npm\node_modules\npmlog with new installed version

    Upgrading... -Error:  npm WARN EBUNDLEOVERRIDE Replacing bundled node_modules\npm\node_modules\read-package-json with ne
    w installed version

    We encountered an error during installation.
    Please consider reporting your trouble to http://aka.ms/npm-issues.
    Here is the error:

    Could not determine npm version.

After the install failed, it completely broke npm and required me to run the Node.js installer to repair the installation. That fixed npm and allowed the script to work the 2nd attempt. But this issue happened on a fresh install of the latest Node.js.

**Comment by felixrieseberg** [comment]
Hey, I'm so sorry about this - thank you for reporting. I'll try to reproduce and fix the issue.

**Comment by nazrhyn** [comment]
:+1:

I did a clean install of NodeJS 5.4.1, then `npm install -g npm-windows-upgrade`. Same error.

**Comment by felixrieseberg** [comment]
Again, thanks for reporting - I confirmed what is going on here. Interestingly, if you do the following, not all module are installed correctly:

 * Install Node 5.4.1
 * Go to `C:\Program Files\nodejs` (where `npm.bat` lives)
 * Run `.\npm install npm@latest`

I'll try to figure out what's going on, but I'm afraid this might be an upstream issue in npm (not that that would be in any way better).

**Comment by felixrieseberg** [comment]
I confirmed [that this is an upstream issue](https://github.com/npm/npm/issues/11088) - npm@3.5.3 and below should be fine. I'll think about a way to warn users about issues like these.

**Comment by nazrhyn** [comment]
Cool. Good detective work; thanks.

**Comment by felixrieseberg** [comment]
Closed in npm.
