### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by centigrade-thomas-becker** [felixrieseberg/npm-windows-upgrade#64]
The [install instructions](https://github.com/felixrieseberg/npm-windows-upgrade#usage) are not entirely clear that **both** command blocks need to be executed from an elevated command shell with administrator privileges. 

The first command in the second block (`npm install -g npm-windows-upgrade`) runs fine without administrator privileges. But the second (`npm-windows-upgrade`) will give you an error:
> NPM cannot be upgraded without administrative rights. To run PowerShell as Administrator,
right-click PowerShell and select 'Run as Administrator'.

That might be a bit pedantic but the instructions should reflect that both command blocks should be executed in an eleveated command shell.

**Comment by felixrieseberg** [comment]
Fair point, I just fixed it ;-)
