### ISSUE TITLE
Error: Could not determine npm version

### ISSUE THREAD

**Issue by ccrowhurstram** [felixrieseberg/npm-windows-upgrade#66]
I'm getting the following error:

> Could not determine npm version.
- I followed the instructions listed [here](https://www.npmjs.com/package/npm-windows-upgrade)
- I ran npm-windows-upgrade using the following command:
  - `npm-windows-upgrade --npm-path "C:\Program Files\nodejs"`
- Once the install errors, I have to reinstall nodejs again on my machine

_Please help (thanks)_

Here are the details of my setup (as output by the tool):

``` cmd
npm-windows-upgrade 1.4.0
? This tool will upgrade npm. Do you want to continue? Yes
? Which version do you want to install? 3.8.0
Upgrading... |

We encountered an error during installation.
Please consider reporting your trouble to http://aka.ms/npm-issues.

Debug Information:

http_parser: 2.6.0
node: 5.2.0
v8: 4.6.85.31
uv: 1.7.5
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2e
os: win32 x64
OS Name: Microsoft Windows 7 Ultimate
OS Version: 6.1.7601 Service Pack 1 Build 7601

Here is the error:

Could not determine npm version.
```

**Comment by felixrieseberg** [comment]
Hey, thanks for reporting - sorry to see that you're having trouble! Do you know if there's anything unique or special about your setup? Can you do me a favor and run `npm -v`? I'd be curious why exactly the script can't find the npm version; and that's the command it's trying to run.

**Comment by ccrowhurstram** [comment]
Thanks for getting back to me.

Once I repaired node, `npm -v` returns 3.5.1

This happens to the version of npm that is installed globally (under my windows profile). 

The version of npm installed in the node directory (C:Program Files\nodejs) is 3.3.12

**Comment by robertbaker** [comment]
@ccrowhurstram sounds like you were using another method to update npm...

This is what I would do and it will fix it.

Uninstall nodejs, not repair!, UNINSTALL.
Go into `%programfiles%\nodejs` and delete the folder.
Delete `%appdata%\npm` and `%appdata%\npm-cache`
Edit your PATH and remove all paths to npm (either program files or appdata).

At this point you should have a blank slate. No node packages, no node in your path, nothing.

So then install the latest node from nodejs.org.

Then in powershell as an admin run `npm i -g npm-windows-upgrade`
then `npm-windows-upgrade` - notice no args....
then update to latest npm. 

Doing that will fix any path edits you have done, remove any duplicate npm installs, etc.

You will have to reinstall any global packages you may have had. But I assure you this is the best way and permanent way to fix it. You don't need a global npm install under your win profile.

**Comment by ccrowhurstram** [comment]
Hey @robertbaker sorry for not replying - somehow I managed to miss your comments :-(

I'll give that a go...

Thanks

**Comment by ccrowhurstram** [comment]
Heads up. Following the instructions by @robertbaker, the upgrade of npm worked. The only extra step I took (as a precaution):

> in the powershell prompt opened above run:  Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force

The end results for me:

1. only **one** installation of npm
2. that installation is:
  * in %programfiles%\nodejs
  * the latest version

**Comment by Matoyak** [comment]
Hey thanks @robertbaker , this fixed my issue as well (was having the same error as @ccrowhurstram ). I had previously run the ```Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force``` command during the broken attempt at using the npm-windows-update tool. Bash Shell is reporting the same version as cmd and powershell now at any rate, which wasn't the case before, so I'm assuming it worked.

**Comment by robertbaker** [comment]
@Matoyak You use this tool, do not use `npm i -g npm`

**Comment by kasarol** [comment]
This exact same issue happened to me today. I was running NPM 7.3.0 and Node 15.5.1 and ran the following commands as PowerShell admin:
```
Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force
npm install -g npm-windows-upgrade
npm-windows-upgrade
```

Selecting the latest NPM version, this resulted in:
```
Error: Could not determine npm version.
    at C:\Users\olli.kasari\AppData\Roaming\npm\node_modules\npm-windows-upgrade\src\versions.js:14:16
    at ChildProcess.exithandler (node:child_process:340:5)
    at ChildProcess.emit (node:events:376:20)
    at maybeClose (node:internal/child_process:1063:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:295:5)
```

After this NPM was completely broken and behaves like this:
```
PS C:\WINDOWS\system32> npm -v
node:internal/modules/cjs/loader:928
  throw err;
  ^

Error: Cannot find module 'is-fullwidth-code-point'
```

Please fix this.
