### ISSUE TITLE
Needed to launch npm-windows-upgrade with node; not hash-bang (#!)

### ISSUE THREAD

**Issue by gkedge** [felixrieseberg/npm-windows-upgrade#67]
From [npm-windows-upgrade](https://github.com/felixrieseberg/npm-windows-upgrade):

> If you have trouble with the script, consider adding parameters manually. A common issue is that the script fails to find npm (and therefore doesn't know where to install it) - in that case, pass the location manually.
> 
> npm-windows-upgrade --npm-path "C:\nodejs"

Not until I used node(1) itself to launch npm-windows-upgrade did it work for me:

$ node .\AppData\Roaming\npm\node_modules\npm-windows-upgrade\bin\npm-windows-upgrade

**Comment by KrauseStefan** [comment]
When installing a global module npm places a `npm-windows-upgrade.cmd` in ` .\AppData\Roaming\npm`

That one should work

**Comment by gkedge** [comment]
Well, that was an excellent hint!  Because, after the global install, though npm-windows-upgrade was in the Roaming\npm\node_modules, there isn't any \npm\npm-windows-upgrade.cmd.  CMD's exist for all the other globals, just not this one.  If it was there, I am guessing it would have been in my %PATH% and found.

So, we know why I couldn't run it from the CLI, but wonder if it's worth looking into why the CMD wasn't created.  I think that might be a waste of time since I just assisted a co-worker with the upgrade and it worked fine for him. I'm gonna close.

Thanks for the hint.
