### ISSUE TITLE
Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by BarryThePenguin** [felixrieseberg/npm-windows-upgrade#7]
Looks like a problem parsing the powershell output. The error occurred just after `Upgrading npm in C:\Program Files\nodejs` appeared in the powershell window.

Upgrade did complete successfully.

```
Upgrading.. \

C:\Users\btp\AppData\Roaming\npm\node_modules\npm-windows-upgrade\bin\npm-windows-upgrade:65
        } else if (output[output.length - 1].indexOf('All done!') > -1) {
                                            ^
TypeError: Cannot read property 'indexOf' of undefined
    at C:\Users\btp\AppData\Roaming\npm\node_modules\npm-windows-upgrade\bin\npm-windows-upgrade:65:45
    at ChildProcess.<anonymous> (C:\Users\btp\AppData\Roaming\npm\node_modules\npm-windows-upgrade\bin\npm-windows-upg
rade:29:9)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
```

**Comment by cchamberlain** [comment]
I am getting this on Windows 8.1 trying to upgrade a custom portable install of npm.

![image](https://cloud.githubusercontent.com/assets/424694/8446562/42c5bda0-1f61-11e5-8e32-18770d22d4ff.png)

**Comment by felixrieseberg** [comment]
Thanks for continued reports - with the thousands of configurations (Windows/Node/npm/Installation/x64 vs x86), I can really use these.

I pushed an update that fixes *this* error. That being said, what is `undefined` here is the output of the updater PS1 script - which doesn't exactly mean great things.
