### ISSUE TITLE
Stalls on "npm-windows-upgrade"

### ISSUE THREAD

**Issue by sam-s4s** [felixrieseberg/npm-windows-upgrade#71]
Hi all

I'm trying to update npm, and I've followed all the steps - everything has worked fine so far, but when I run the "npm-windows-upgrade" command, it prints out "npm-windows-upgrade 2.2.2" and then just stops at the command line, forever. The cursor is just flashing, but nothing is happening. I have tried it a few times, no luck.

Running in Powershell, on Windows 10, remote desktop to a Hyper-V virtual machine. Hoping it'll upgrade my system's npm, and the copy inside Visual Studio 2015.

**Comment by felixrieseberg** [comment]
Hm, that's weird - it should at least go straight to confirmation. Which version of Node are you running?

**Comment by sam-s4s** [comment]
Node version 4.4.2

Interestingly enough, I tried doing npm-windows-upgrade from command prompt instead of powershell - and it worked straight away! :D

Strange that it didn't work in Powershell???

**Comment by felixrieseberg** [comment]
If you can find the location of npm, you can pass it to the tool using the `-n, --npm-path` parameter.

**Comment by Bitart** [comment]
Hi,

Dont hesitate in consider folder and sub folders windows permissions. I
just solved that problem, before, solving such curious situation (adding
write privileges to LOGGEDED IN USERS) even executing as Administrator.

Fabiano Viana

**Comment by GaTechThomas** [comment]
Same problem here running in PowerShell. It echoes "npm-windows-upgrade" then freezes. I'm on node 4.4.4.

**Comment by sam-s4s** [comment]
Workaround GaTech:
After you've done the other commands in PowerShell, you can then do the "npm-windows-upgrade" in a command prompt with admin.
