### ISSUE TITLE
Install latest NPM with no prompts option?

### ISSUE THREAD

**Issue by robertbaker** [felixrieseberg/npm-windows-upgrade#72]
`npm-windows-upgrade -p -v 3.8.9`  // works

`npm-windows-upgrade -p -v latest` // doesn't

Is there a way to auto install the newest version of NPM without knowing the version number automatically?

**Comment by felixrieseberg** [comment]
Not right now, but we can probably make that work 👍

**Comment by felixrieseberg** [comment]
...aaaaaand done! Thanks for the tip!

**Comment by wulf2468** [comment]
@felixrieseberg Probably should mention this functionality in the README.md. It's a very useful feature, especially for automation. Thanks for adding it! :+1:
