### ISSUE TITLE
"npm install -g npm-windows-upgrade" does not work on machines without access to registry.npmjs.org

### ISSUE THREAD

**Issue by KrauseStefan** [felixrieseberg/npm-windows-upgrade#73]
We have a custom npm repository from where we get all our npm packages.

Access to `registry.npmjs.org` is blocked by our firewall.

Is it possible to talk you into deleting the shrinkwrap.json file?

We use the `npm --registry <nexus server>` option to install all packages.

Currently I have a fork of this repository with it removed https://github.com/KrauseStefan/npm-windows-upgrade

**Comment by KrauseStefan** [comment]
Alternatively implementing something like the angular team has done would properly also work. This effectively removes the resolve url from the shrinkwrap, but keeps the version.

See:
https://github.com/angular/angular.js/commit/f684cb09a56d44c0814eda7e1613ecf4d2c5da15#commitcomment-5731712

**Comment by felixrieseberg** [comment]
Hey, fair points - I think we can try to remove it and see if anyone's running into trouble without it. Let me update the package.json with more strict instructions and push a new minor!

**Comment by felixrieseberg** [comment]
Alright, done! Give `2.3.0` a try, it should do the trick for you!

**Comment by KrauseStefan** [comment]
Thank you, I works great in our environment :)
