### ISSUE TITLE
Installation hangs with 'Upgrading...'

### ISSUE THREAD

**Issue by erinev** [felixrieseberg/npm-windows-upgrade#75]
Hi @felixrieseberg,
I did all steps -> https://www.npmjs.com/package/npm-windows-upgrade#fix-an-attempted-upgrade

then installing according manual:
1) PowerShell and select Run as Administrator -> OK
2) npm install --global --production npm-windows-upgrade -> OK
3) npm-windows-upgrade 
  a) write Y -> OK
  b) choose 3.9.6 -> 'Upgrading...' and process never ends -> http://screencast.com/t/uQ0LTlnRl

Windows 10, powershell 5, installed v6.2.1 node so i got default v1.4.9 npm with it (and trying to upgrade it)

what could be the problem ?

**Comment by jhoralek** [comment]
have the same issue
