### ISSUE TITLE
Error installing npm-windows-upgrade

### ISSUE THREAD

**Issue by stoberman37** [felixrieseberg/npm-windows-upgrade#83]
Debug Information:

http_parser: 2.3node: 0.12.2v8: 3.28.73uv: 1.4.2-node1zlib: 1.2.8modules: 14openssl: 1.0.1mos: win32 ia32OS Name: Microsoft Windows 7 Enterprise
OS Version: 6.1.7601 Service Pack 1 Build 7601

**Comment by stoberman37** [comment]
Contents of npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'npm-windows-upgrade' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files (x86)\nodejs\\node.exe
5 verbose stack Error: ENOENT, open 'C:\package.json'
5 verbose stack     at Error (native)
6 verbose cwd C:\
7 error Windows_NT 6.1.7601
8 error argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "npm-windows-upgrade"
9 error node v0.12.2
10 error npm  v2.7.4
11 error path C:\package.json
12 error code ENOENT
13 error errno -4058
14 error enoent ENOENT, open 'C:\package.json'
14 error enoent This is most likely not a problem with npm itself
14 error enoent and is related to npm not being able to find a file.
15 verbose exit [ -4058, true ]

**Comment by felixrieseberg** [comment]
Thanks for reporting! Can you tell me which commands you ran?

**Comment by stoberman37** [comment]
Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force

npm install --global --production npm-windows-upgrade
npm-windows-upgrade

**Comment by stoberman37** [comment]
I ran it in c:\ and in c:\windows\system32.  Trying again clean in c:\users\<myusername>

**Comment by stoberman37** [comment]
the install appears to succeed.  

C:\Users\scottob>npm install --global --production npm-windows-upgrade
C:\Users\scottob\AppData\Roaming\npm\npm-windows-upgrade -> C:\Users\scottob\AppData\Roaming\npm\node_modules\npm-window
s-upgrade\bin\npm-windows-upgrade.js
npm-windows-upgrade@3.0.3 C:\Users\scottob\AppData\Roaming\npm\node_modules\npm-windows-upgrade
├── cli-spinner@0.2.5
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── chalk@1.1.3 (escape-string-regexp@1.0.5, supports-color@2.0.0, ansi-styles@2.2.1, has-ansi@2.0.0, strip-ansi@3.0.1)
├── promise@7.1.1 (asap@2.0.4)
├── prompt@1.0.0 (read@1.0.7, revalidator@0.1.8, colors@1.1.2, pkginfo@0.4.0, winston@2.1.1, utile@0.3.0)
├── regenerator-runtime-only@0.8.38 (promise@6.1.0, es6-symbol@2.0.1)
├── inquirer@1.0.3 (ansi-escapes@1.4.0, mute-stream@0.0.6, through@2.3.8, strip-ansi@3.0.1, figures@1.7.0, pinkie-promis
e@2.0.1, cli-width@2.1.0, run-async@2.2.0, string-width@1.0.1, cli-cursor@1.0.2, rx@4.1.0, lodash@4.13.1)
└── babel-polyfill@6.9.1 (regenerator-runtime@0.9.5, babel-runtime@6.9.2, core-js@2.4.0)

**Comment by stoberman37** [comment]
running npm-windows-upgrade command fails

C:\Users\scottob>npm-windows-upgrade
npm-windows-upgrade v3.0.3
Upgrading npm... |Checked system for npm installation:
According to PowerShell: C:\Program Files (x86)\nodejs
According to npm:        C:\Users\scottob\AppData\Roaming\npm
Decided that npm is installed in C:\Program Files (x86)\nodejs
Upgrading npm... /? Which version do you want to install? (Use arrow keys)
> 3.10.3
  3.10.2
  3.10.1
  3.10.0
  3.9.6
  3.9.5
  3.9.4
Upgrading npm... \

Upgrading npm (fallback method)... \

We encountered an error during installation.
Please consider reporting your trouble to http://aka.ms/npm-issues.

Debug Information:

http_parser: 2.3node: 0.12.2v8: 3.28.73uv: 1.4.2-node1zlib: 1.2.8modules: 14openssl: 1.0.1mos: win32 ia32OS Name: Microsoft Windows 7 Enterprise
OS Version: 6.1.7601 Service Pack 1 Build 7601

**Comment by stoberman37** [comment]
ok thanks

**Comment by radioflyer651** [comment]
I was getting the same problem. In fact, aside from running Windows 10 Home, my output was looking almost identical as the OP's.  Forgive my newbie-ness, but while I cannot find the log now to double check what I saw, I had opened it before my successful install, and noticed that it had npm@'undefined', where I would have expected the version.  (Again, I'm totally green here.)

The output showed version 3.10.4 as the version, so I tried installing using version 3.10.3.  It worked!

I attempted to upgrade to the highest version again (3.10.4), and it still failed.

I'm not sure if this info is helpful to you, but below is my Windows PowerShell interactions, just in case.



Windows PowerShell
Copyright (C) 2015 Microsoft Corporation. All rights reserved.

PS C:\WINDOWS\system32> Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force
PS C:\WINDOWS\system32> npm install --global --production npm-windows-upgrade
C:\Users\Richard\AppData\Roaming\npm\npm-windows-upgrade -> C:\Users\Richard\AppData\Roaming\npm\node_modules\npm-window
s-upgrade\bin\npm-windows-upgrade.js
npm-windows-upgrade@3.0.3 C:\Users\Richard\AppData\Roaming\npm\node_modules\npm-windows-upgrade
├── cli-spinner@0.2.5
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── promise@7.1.1 (asap@2.0.4)
├── chalk@1.1.3 (supports-color@2.0.0, ansi-styles@2.2.1, escape-string-regexp@1.0.5, strip-ansi@3.0.1, has-ansi@2.0.0)
├── prompt@1.0.0 (revalidator@0.1.8, pkginfo@0.4.0, colors@1.1.2, read@1.0.7, winston@2.1.1, utile@0.3.0)
├── regenerator-runtime-only@0.8.38 (promise@6.1.0, es6-symbol@2.0.1)
├── inquirer@1.0.3 (ansi-escapes@1.4.0, mute-stream@0.0.6, through@2.3.8, strip-ansi@3.0.1, cli-width@2.1.0, pinkie-prom
ise@2.0.1, figures@1.7.0, run-async@2.2.0, string-width@1.0.1, cli-cursor@1.0.2, rx@4.1.0, lodash@4.13.1)
└── babel-polyfill@6.9.1 (regenerator-runtime@0.9.5, babel-runtime@6.9.2, core-js@2.4.0)
PS C:\WINDOWS\system32> npm-windows-upgrade
npm-windows-upgrade v3.0.3
Upgrading npm... /Checked system for npm installation:
According to PowerShell: C:\Program Files\nodejs
According to npm:        C:\Users\Richard\AppData\Roaming\npm
Decided that npm is installed in C:\Program Files\nodejs
Upgrading npm... /? Which version do you want to install? (Use arrow keys)
> 3.10.4
  3.10.3
  3.10.2
  3.10.1
  3.10.0
  3.9.6
  3.9.5
Upgrading npm... /

Upgrading npm (fallback method)... |

We encountered an error during installation.
Please consider reporting your trouble to http://aka.ms/npm-issues.

Debug Information:

http_parser: 2.5.2node: 4.4.1v8: 4.5.103.35uv: 1.8.0zlib: 1.2.8ares: 1.10.1-DEVicu: 56.1modules: 46openssl: 1.0.2gos: wi
n32 x64OS Name: Microsoft Windows 10 Home
OS Version: 10.0.10586 N/A Build 10586

PS C:\WINDOWS\system32> npm-windows-upgrade -v

  error: option `-v, --npm-version <version>' argument missing

PS C:\WINDOWS\system32> npm-windows-upgrade -V
3.0.3
PS C:\WINDOWS\system32> npm-windows-upgrade -v 3.10.3
npm-windows-upgrade v3.0.3
Upgrading npm... -Checked system for npm installation:
According to PowerShell: C:\Program Files\nodejs
According to npm:        C:\Users\Richard\AppData\Roaming\npm
Decided that npm is installed in C:\Program Files\nodejs
Upgrading npm... -

Upgrade finished. Your new npm version is 3.10.3. Have a nice day!
PS C:\WINDOWS\system32> npm-windows-upgrade
npm-windows-upgrade v3.0.3
Upgrading npm... /Checked system for npm installation:
According to PowerShell: C:\Program Files\nodejs
According to npm:        C:\Users\Richard\AppData\Roaming\npm
Decided that npm is installed in C:\Program Files\nodejs
Upgrading npm... \? Which version do you want to install? (Use arrow keys)
> 3.10.4
  3.10.3
  3.10.2
  3.10.1
  3.10.0
  3.9.6
  3.9.5
Upgrading npm... |

Upgrading npm (fallback method)... -

We encountered an error during installation.
Please consider reporting your trouble to http://aka.ms/npm-issues.

Debug Information:

http_parser: 2.5.2node: 4.4.1v8: 4.5.103.35uv: 1.8.0zlib: 1.2.8ares: 1.10.1-DEVicu: 56.1modules: 46openssl: 1.0.2gos: wi
n32 x64OS Name: Microsoft Windows 10 Home
OS Version: 10.0.10586 N/A Build 10586

PS C:\WINDOWS\system32>

**Comment by dshorowitz** [comment]
Having the exact same issue here. Win 10 Professional.

**Comment by robertbaker** [comment]
For those that have problems, make sure you read and do this: https://github.com/felixrieseberg/npm-windows-upgrade#fix-an-attempted-upgrade

**Comment by HarveyWilliams** [comment]
I ran all of the steps to fix an attempted upgrade.

Reinstalled Node (v4.4.7).

Ran:
```
Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force
npm install --global --production npm-windows-upgrade
npm-windows-upgrade
```

It eventually goes to the fallback method, which then fails.

I have uploaded a video displaying this: https://www.youtube.com/watch?v=jQw_lU82qYI

**Comment by HarveyWilliams** [comment]
The first time I tried running the update package, I got some error with the npm-cli.js file. I think I ignored the error and it didn't popup the second time I ran the package.

However, with another computer, I got this message:

![npm-cli](https://cloud.githubusercontent.com/assets/7733459/17644686/1df91e92-6185-11e6-97fc-fca9078a4c99.png)

Debug information:

```
http_parser: 2.7.0node: 6.2.1v8: 5.0.71.52uv: 1.9.1zlib: 1.2.8ares: 1.10.1-DEVicu: 57.1modules: 48openssl: 1.0.2hos: win32 x64OS Name: Microsoft Windows 10 Pro
OS Version: 10.0.14393 N/A Build 14393
```
