### ISSUE TITLE
Removed npm when trying to upgrade, no error messages

### ISSUE THREAD

**Issue by xargi** [felixrieseberg/npm-windows-upgrade#84]
Ran the following in an admin shell

```
PS C:\Windows\system32> npm-windows-upgrade.cmd
npm-windows-upgrade v3.0.3
Upgrading npm... |Checked system for npm installation:
According to PowerShell: C:\Program Files\nodejs
According to npm:        C:\Program Files\nodejs
Decided that npm is installed in C:\Program Files\nodejs
Upgrading npm... /? Which version do you want to install? (Use arrow keys)
> 3.10.4
  3.10.3
  3.10.2
  3.10.1
? Which version do you want to install? 3.10.4
PS C:\Windows\system32> npm-windows-upgrade.cmd
npm-windows-upgrade v3.0.3
Upgrading npm... -Checked system for npm installation:
According to PowerShell:
According to npm:
Decided that npm is not installed in either, but attempting to install in
Upgrading npm... \

Could not determine npm version.
PS C:\Windows\system32>
```

I didn't press any key after getting the "Which version do you want to install"-prompt, but the upgrader advanced regardless. It did not, however, upgrade my npm, it simply removed the npm (v2.14.12, node v4.2.5) installation I already had in the folder that it found.

Windows 7, PS 2

Also in case it matters, I am using nvm and `C:\Program Files\nodejs` is a link.

**Comment by robertbaker** [comment]
I'm not sure if NVM is supported (probably isn't). You won't be able to use npm v3+ on that version of node anyway.

If you don't need NVM, I would follow this guide: https://github.com/felixrieseberg/npm-windows-upgrade#fix-an-attempted-upgrade

then install the latest node v6.

**Comment by xargi** [comment]
I installed npm 3.10.3 manually afterwards and it seems to be working fine regardless of the node version, but upgrading the node version would have been trivial anyway. It would be nice to get an error prompt or some kind of message in the above situation though (instead of leaving the user on nothing).
