### ISSUE TITLE
Limited up to 3.10.6 npm version

### ISSUE THREAD

**Issue by 462960** [felixrieseberg/npm-windows-upgrade#86]
I need npm 4.4.7 but, sorry to say it limited, as you can see.
Is there any way forward? 
![npm](https://cloud.githubusercontent.com/assets/10447862/17168022/cae03262-53e8-11e6-9e44-d214c46f682f.png)
,

**Comment by felixrieseberg** [comment]
Hey, there's no npm 4 - are you thinking of Node by any chance? This tool just upgrades npm, not Node.
