### ISSUE TITLE
Unable to install npm Windows 7 64 bit

### ISSUE THREAD

**Issue by sumitsoman** [felixrieseberg/npm-windows-upgrade#9]
Am getting this error

![error](https://cloud.githubusercontent.com/assets/5772710/8470726/7ac83244-20ad-11e5-9cde-410b34a3634b.png)

How to resolve, am trying to install phonegap after installing node.js (64 bit), which gives this error
32 error node v0.12.5
33 error npm  v2.11.2

**Comment by cchamberlain** [comment]
Can you please post the contents of "C:\Windows\system32\npm-debug.log"?

**Comment by sumitsoman** [comment]
I have posted the log on this link
https://github.com/npm/npm/issues/8799

**Comment by sumitsoman** [comment]
i have posted the log here
https://github.com/npm/npm/issues/8799

**Comment by cchamberlain** [comment]
Can you try running `npm config set ca=""` first per [this](http://blog.npmjs.org/post/78165272245/more-help-with-self-signed-cert-in-chain-and-npm) and retry?

**Comment by sumitsoman** [comment]
this works as of now, thanks!
