### ISSUE TITLE
arrow keys do not respond

### ISSUE THREAD

**Issue by GaryB432** [felixrieseberg/npm-windows-upgrade#93]
This promising app (v3.1.0) helpfully says "use arrow keys" but my up/down arrow keys seem to do nothing. I've tried elevated powershell and elevated cmd.  I'm on Windows 10.0.14393.   Is there something I should check?

**Comment by felixrieseberg** [comment]
Hey! I'm sorry to hear that you're having trouble - are you using PowerShell or CMD? To fix your issues (for now), you can pass the version you'd like to install as a parameter. Not perfect, but it might help you out until we get to the bottom of this.

**Comment by GaryB432** [comment]
I tried both elevated PS and elevated cmd, both unelevated too.Lucky me, the default version listed first took off when I pressed Enter which worked, unlike the arrow keys. I don't seem to have any other problems with my arrows in other interactive js apps like yeoman for instance. But I don't know if it's using `prompt`. btw thanks for this. It's a nice piece of work.

**Comment by GaryB432** [comment]
I should clarify that the other prompt-y thing I like, [the yeoman scaffold generator](https://yeoman.io), also _does not work_. I thought I might have hardware keyboard trouble but I remoted into my Windows 10 problem machine and arrow keys still do not respond. The arrows work great in all other apps like my text editor. All is well on my Windows 7 machine.

**Comment by felixrieseberg** [comment]
I updated all dependencies and _hope_ that it should fix the issue.

**Comment by GaryB432** [comment]
Looking good.  Thanks!
