### ISSUE TITLE
Weird, unexpected output.

### ISSUE THREAD

**Issue by 462960** [felixrieseberg/npm-windows-upgrade#94]
1) Which version npm would you like? 3.10.8
    OK, please, have 3.10.6
2) Thanks, I'll run npm-windows-upgrade one more time.
    Unexpected error .

Please, what's wrong?
![npm version](https://cloud.githubusercontent.com/assets/10447862/18865231/c885a3e0-84a2-11e6-8cdc-9c235866d329.jpg)

**Comment by felixrieseberg** [comment]
🤔  What the hell? I'm sorry that you're having this trouble - this makes no sense. It seems like npm's version server had a hickup or something? The unexpected end of input you're seeing there is us receiving garbage from npm.

Was this a one-time-only thing or are you still seeing this error?

**Comment by 462960** [comment]
Thanks for response.
The main trouble is that since that moment something has been going wrong with npm.
Most of npm based command require miraculous "mime-db" module.  
I have not reinstalled Node yet but, definitely, I'm forced to do it.

What would be your advise?
