### ISSUE TITLE
Safer way to allow execution policy

### ISSUE THREAD

**Issue by Eibwen** [felixrieseberg/npm-windows-upgrade#95]
Open command OR powershell with "Run As Administrator", then run the command
`powershell -ExecutionPolicy unrestricted` 

This opens a new shell, generally inside the same console, that is unrestricted, and only changes the ExecutionPolicy for that specific powershell shell, not for the CurrentUser.  Although must be done every time one wants to use npm-windows-upgrade.

Source: https://blogs.technet.microsoft.com/ken_brumfield/2014/01/19/simple-way-to-temporarily-bypass-powershell-execution-policy/

**Comment by krokofant** [comment]
@felixrieseberg Why was this closed?
